package com.example.mienspav7.model;

public enum ERole {
	ROLE_USER,
	ROLE_MODERATOR,
	ROLE_ADMIN,
	ROLE_CATEGORY,
	ROLE_ORDER_SERVICE,
	ROLE_ORDER_PRODUCT,
	ROLE_PRODUCT,
	ROLE_SERVICE,
	ROLE_SHOPINFOR,
	ROLE_ACCOUNT
}
