package com.example.mienspav7.model;
// Generated Feb 17, 2023, 1:38:16 PM by Hibernate Tools 3.6.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRole generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "user_role", catalog = "mienspa3")
public class UserRole implements java.io.Serializable {

	private Integer usrId;
	private Role role;
	private Users users;
	private Date createdAt;
	private Date updatedAt;

	public UserRole() {
	}

	public UserRole(Role role, Users users) {
		this.role = role;
		this.users = users;
	}

	public UserRole(Role role, Users users, Date createdAt, Date updatedAt) {
		this.role = role;
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "usr_Id", unique = true, nullable = false)
	public Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usr_RoleId", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usr_UserId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
